RESULT = min-caml
SOURCES = id.ml type.ml m.ml s.ml syntax.ml \
		  typing.ml lexer.mll parser.mly \
		  normal.ml \
		  alpha.ml alias.ml elim.ml inline.ml constFold.ml \
		  closure.ml asm.ml emit.ml virtual.ml simulate.ml \
		  main.ml

include OCamlMakefile
